apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "redis.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.metrics.enabled }}
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: mariadb
    port: 3305
    targetPort: 3306
    protocol: TCP
  selector:
    app: {{ template "redis.fullname" . }}
  type: NodePort
